name: Frontend CD Pipeline

on:
  workflow_run:
    workflows: ["Frontend CI Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-and-dast:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Deploy to Cluster
        run: |
          echo "Deploying the latest version of the app..."
          kubectl apply -f k8s/
          
      - name: DAST (Dynamic Security Testing)
        run: |
          echo "Running DAST scan..."
          # DAST typically requires a live URL. This is a placeholder.
          # Example: npx zap-cli scan http://your-live-app.com
        continue-on-error: true
