# .github/workflows/ci-cd-docker-push.yml
name: Push Docker Image

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: "yaswanthmitta"
  IMAGE_NAME: multiapp-frontend

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:latest .
          docker build -t ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

          docker push ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}